# tcn75test.py
# reads I2C data generated by tempoerature sensor TCN75
# VP 2.6.2025
#
# install I2C support for python first
# sudo pip install smbus2
# pip install adafruit-blinka
# 
# edit /boot/config.txt
# intf:fiq_debugger=on
# intf:uart0=on
# intf:uart4=on
# intf:i2c6=on
# #intf:i2c7=off


import smbus2
import time

# Define I2C parameters
I2C_BUS = 6  # Tinker Board 2S I2C bus 6
TCN75_ADDRESS = 0x48  # Default I2C address of TCN75
TEMP_REGISTER = 0x00  # Temperature register

# Initialize the I2C bus
bus = smbus2.SMBus(I2C_BUS)

def read_temperature():
    """Reads temperature from the TCN75 sensor in Celsius."""
    raw_data = bus.read_word_data(TCN75_ADDRESS, TEMP_REGISTER)

    # Swap bytes (TCN75 stores MSB first)
    raw_data = ((raw_data << 8) & 0xFF00) | (raw_data >> 8)

    # Extract temperature value (only upper byte is relevant)
    temp_celsius = raw_data >> 4  # TCN75 uses 12-bit resolution

    # Handle negative temperatures (two's complement format)
    if temp_celsius & (1 << 11):
        temp_celsius -= 1 << 12

    return temp_celsius * 0.0625  # Convert to Celsius

try:
    while True:
        temperature = read_temperature()
		# one decimal output
        print(f"Temperature: {temperature:.1f} °C")
        time.sleep(5)  # Read every second
except KeyboardInterrupt:
    print("Program stopped by user.")
    bus.close()
